sudo: false
dist: trusty
language: ruby

before_install:
  - gem install bundler -v 1.17.3

install:
  - bundle _1.17.3_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bundle exec rspec
  - bundle exec cucumber

rvm:
  - "2.5"
  - "2.4"
  - "2.3"
  - "2.2.2"
  - "ruby-head"
  - "jruby"
  - "jruby-head"

gemfile:
  - gemfiles/rails-5.2.gemfile

matrix:
  include:
    - rvm: "2.5"
      gemfile: gemfiles/rails-head.gemfile

    - rvm: "2.5"
      gemfile: gemfiles/rails-5.1.gemfile

    - rvm: "2.5"
      gemfile: gemfiles/rails-5.0.gemfile

    - rvm: "2.5"
      gemfile: gemfiles/rails-4.2.gemfile

    # Test Rails 4.0–4.1 against Ruby 2.3
    - rvm: "2.3"
      gemfile: gemfiles/rails-4.1.gemfile

    - rvm: "2.3"
      gemfile: gemfiles/rails-4.0.gemfile

  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
    - rvm: "jruby"
    - gemfile: gemfiles/rails-head.gemfile
