= UriFormatValidator

image:https://img.shields.io/gem/v/uri_format_validator.svg[
	Gem Version, link="https://rubygems.org/gems/uri_format_validator"]
image:https://img.shields.io/travis/riboseinc/uri_format_validator/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/uri_format_validator"]
image:https://img.shields.io/codeclimate/github/riboseinc/uri_format_validator.svg[
	"Code Climate", link="https://codeclimate.com/github/riboseinc/uri_format_validator"]

Validate URL formats in ActiveModels.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'uri_format_validator'
----

And then execute:

....
$ bundle
....

Or install it yourself as:

....
$ gem install uri_format_validator
....

== Usage

Add the following to your model:

[source,ruby]
----
validates :my_url_attribute, uri_format: true
----

Also, an old-fashioned validation helper is provided:

[source,ruby]
----
validates_url_format_of :my_url_attribute
----

== Error messages

You can set the error message as an additional parameter

[source,ruby]
----
validates :my_url_attribute, uri_format: true, message: 'is not a valid URL'
----

or you can use locales:

[source,yaml]
----
en:
  errors:
    messages:
      invalid_uri: 'is not a valid URL'
----

== Development

After checking out the repo, run `bin/setup` to install dependencies.
Then, run `rake spec` to run the tests. You can also run `bin/console`
for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run
`bundle exec rake install`. To release a new version, update the version
number in `version.rb`, and then run `bundle exec rake release`, which
will create a git tag for the version, push git commits and tags, and
push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/riboseinc/uri_format_validator. This project is intended to
be a safe, welcoming space for collaboration, and contributors are
expected to adhere to the http://contributor-covenant.org[Contributor
Covenant] code of conduct.

== License

The gem is available as open source under the terms of the
http://opensource.org/licenses/MIT[MIT License].
